name: Daily Commit

on:
  schedule:
    - cron: '17 3 * * *' # Runs every day at 03:17 UTC
  workflow_dispatch:     # Enables manual trigger

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make dummy change
        run: |
          echo "Commit on $(date)" >> commit-log.txt

      - name: Commit by 24f1001492@ds.study.iitm.ac.in
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "24f1001492@ds.study.iitm.ac.in"
          git add commit-log.txt
          git commit -m "Automated daily commit on $(date)"
          git push
