name: Daily Commit

on:
  schedule:
    - cron: '30 4 * * *'  # runs every day at 4:30 UTC
  workflow_dispatch:

permissions:
  contents: write  # 🔥 Required for pushing commits

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set git identity (24f1001492@ds.study.iitm.ac.in)
        run: |
          git config user.name "GitHub Action"
          git config user.email "24f1001492@ds.study.iitm.ac.in"

      - name: Make a daily commit
        run: |
          date >> daily-log.txt
          git add daily-log.txt
          git commit -m "Daily commit: $(date)"
          git push
